version: '3'
volumes:
  alsupport-db:
services:
  alsupport:
    image: thecodingmachine/php:7.4-v4-apache-node14
    container_name: alsupport
    ports:
      - "8110:80"
      - "3000:3000"
      - "3121:3001"
    volumes:
      - .:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: public/
      PHP_EXTENSION_GD: 1
      PHP_EXTENSION_SQLITE3: 1
      PHP_EXTENSION_PDO_SQLITE: 1
  alsupport-db:
    image: mysql:5.7
    ports:
      - "3332:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: alsupport
      MYSQL_USER: alsupport
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - alsupport-db:/var/lib/mysql
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1050:1025 # smtp server
      - 8050:8025 # web ui
